GET  http://localhost:8080/events/registrations
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhbnN5QGdtYWlsLmNvbSIsImV4cGlyeSI6MTcxOTczNzQyMSwidXNlcklkIjoxfQ.1EJUL0dqs3Tnmei2JigNI8dIf7QHCQD7imQmx_8T2Ls
